<?xml version="1.0" encoding="UTF-8" ?>
<Package name="NTU_Dialog" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs>
        <Dialog name="topic_dialog" src="topic_dialog/topic_dialog.dlg" />
    </Dialogs>
    <Resources>
        <File name="DESCRIPTION" src="lib/beautifulsoup4-4.6.0.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/beautifulsoup4-4.6.0.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/beautifulsoup4-4.6.0.dist-info/METADATA" />
        <File name="RECORD" src="lib/beautifulsoup4-4.6.0.dist-info/RECORD" />
        <File name="WHEEL" src="lib/beautifulsoup4-4.6.0.dist-info/WHEEL" />
        <File name="metadata" src="lib/beautifulsoup4-4.6.0.dist-info/metadata.json" />
        <File name="top_level" src="lib/beautifulsoup4-4.6.0.dist-info/top_level.txt" />
        <File name="DESCRIPTION" src="lib/bitly_api-0.3.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/bitly_api-0.3.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/bitly_api-0.3.dist-info/METADATA" />
        <File name="RECORD" src="lib/bitly_api-0.3.dist-info/RECORD" />
        <File name="WHEEL" src="lib/bitly_api-0.3.dist-info/WHEEL" />
        <File name="metadata" src="lib/bitly_api-0.3.dist-info/metadata.json" />
        <File name="top_level" src="lib/bitly_api-0.3.dist-info/top_level.txt" />
        <File name="zip-safe" src="lib/bitly_api-0.3.dist-info/zip-safe" />
        <File name="__init__" src="lib/bitly_api/__init__.py" />
        <File name="bitly_api" src="lib/bitly_api/bitly_api.py" />
        <File name="bitly_http" src="lib/bitly_api/bitly_http.py" />
        <File name="__init__" src="lib/bs4/__init__.py" />
        <File name="__init__" src="lib/bs4/builder/__init__.py" />
        <File name="_html5lib" src="lib/bs4/builder/_html5lib.py" />
        <File name="_htmlparser" src="lib/bs4/builder/_htmlparser.py" />
        <File name="_lxml" src="lib/bs4/builder/_lxml.py" />
        <File name="dammit" src="lib/bs4/dammit.py" />
        <File name="diagnose" src="lib/bs4/diagnose.py" />
        <File name="element" src="lib/bs4/element.py" />
        <File name="testing" src="lib/bs4/testing.py" />
        <File name="__init__" src="lib/bs4/tests/__init__.py" />
        <File name="test_builder_registry" src="lib/bs4/tests/test_builder_registry.py" />
        <File name="test_docs" src="lib/bs4/tests/test_docs.py" />
        <File name="test_html5lib" src="lib/bs4/tests/test_html5lib.py" />
        <File name="test_htmlparser" src="lib/bs4/tests/test_htmlparser.py" />
        <File name="test_lxml" src="lib/bs4/tests/test_lxml.py" />
        <File name="test_soup" src="lib/bs4/tests/test_soup.py" />
        <File name="test_tree" src="lib/bs4/tests/test_tree.py" />
        <File name="DESCRIPTION" src="lib/certifi-2017.11.5.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/certifi-2017.11.5.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/certifi-2017.11.5.dist-info/METADATA" />
        <File name="RECORD" src="lib/certifi-2017.11.5.dist-info/RECORD" />
        <File name="WHEEL" src="lib/certifi-2017.11.5.dist-info/WHEEL" />
        <File name="metadata" src="lib/certifi-2017.11.5.dist-info/metadata.json" />
        <File name="top_level" src="lib/certifi-2017.11.5.dist-info/top_level.txt" />
        <File name="__init__" src="lib/certifi/__init__.py" />
        <File name="__main__" src="lib/certifi/__main__.py" />
        <File name="cacert" src="lib/certifi/cacert.pem" />
        <File name="core" src="lib/certifi/core.py" />
        <File name="old_root" src="lib/certifi/old_root.pem" />
        <File name="weak" src="lib/certifi/weak.pem" />
        <File name="DESCRIPTION" src="lib/chardet-3.0.4.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/chardet-3.0.4.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/chardet-3.0.4.dist-info/METADATA" />
        <File name="RECORD" src="lib/chardet-3.0.4.dist-info/RECORD" />
        <File name="WHEEL" src="lib/chardet-3.0.4.dist-info/WHEEL" />
        <File name="entry_points" src="lib/chardet-3.0.4.dist-info/entry_points.txt" />
        <File name="metadata" src="lib/chardet-3.0.4.dist-info/metadata.json" />
        <File name="top_level" src="lib/chardet-3.0.4.dist-info/top_level.txt" />
        <File name="__init__" src="lib/chardet/__init__.py" />
        <File name="big5freq" src="lib/chardet/big5freq.py" />
        <File name="big5prober" src="lib/chardet/big5prober.py" />
        <File name="chardistribution" src="lib/chardet/chardistribution.py" />
        <File name="charsetgroupprober" src="lib/chardet/charsetgroupprober.py" />
        <File name="charsetprober" src="lib/chardet/charsetprober.py" />
        <File name="__init__" src="lib/chardet/cli/__init__.py" />
        <File name="chardetect" src="lib/chardet/cli/chardetect.py" />
        <File name="codingstatemachine" src="lib/chardet/codingstatemachine.py" />
        <File name="compat" src="lib/chardet/compat.py" />
        <File name="cp949prober" src="lib/chardet/cp949prober.py" />
        <File name="enums" src="lib/chardet/enums.py" />
        <File name="escprober" src="lib/chardet/escprober.py" />
        <File name="escsm" src="lib/chardet/escsm.py" />
        <File name="eucjpprober" src="lib/chardet/eucjpprober.py" />
        <File name="euckrfreq" src="lib/chardet/euckrfreq.py" />
        <File name="euckrprober" src="lib/chardet/euckrprober.py" />
        <File name="euctwfreq" src="lib/chardet/euctwfreq.py" />
        <File name="euctwprober" src="lib/chardet/euctwprober.py" />
        <File name="gb2312freq" src="lib/chardet/gb2312freq.py" />
        <File name="gb2312prober" src="lib/chardet/gb2312prober.py" />
        <File name="hebrewprober" src="lib/chardet/hebrewprober.py" />
        <File name="jisfreq" src="lib/chardet/jisfreq.py" />
        <File name="jpcntx" src="lib/chardet/jpcntx.py" />
        <File name="langbulgarianmodel" src="lib/chardet/langbulgarianmodel.py" />
        <File name="langcyrillicmodel" src="lib/chardet/langcyrillicmodel.py" />
        <File name="langgreekmodel" src="lib/chardet/langgreekmodel.py" />
        <File name="langhebrewmodel" src="lib/chardet/langhebrewmodel.py" />
        <File name="langhungarianmodel" src="lib/chardet/langhungarianmodel.py" />
        <File name="langthaimodel" src="lib/chardet/langthaimodel.py" />
        <File name="langturkishmodel" src="lib/chardet/langturkishmodel.py" />
        <File name="latin1prober" src="lib/chardet/latin1prober.py" />
        <File name="mbcharsetprober" src="lib/chardet/mbcharsetprober.py" />
        <File name="mbcsgroupprober" src="lib/chardet/mbcsgroupprober.py" />
        <File name="mbcssm" src="lib/chardet/mbcssm.py" />
        <File name="sbcharsetprober" src="lib/chardet/sbcharsetprober.py" />
        <File name="sbcsgroupprober" src="lib/chardet/sbcsgroupprober.py" />
        <File name="sjisprober" src="lib/chardet/sjisprober.py" />
        <File name="universaldetector" src="lib/chardet/universaldetector.py" />
        <File name="utf8prober" src="lib/chardet/utf8prober.py" />
        <File name="version" src="lib/chardet/version.py" />
        <File name="DESCRIPTION" src="lib/cloudinary-1.8.0.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/cloudinary-1.8.0.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/cloudinary-1.8.0.dist-info/METADATA" />
        <File name="RECORD" src="lib/cloudinary-1.8.0.dist-info/RECORD" />
        <File name="WHEEL" src="lib/cloudinary-1.8.0.dist-info/WHEEL" />
        <File name="metadata" src="lib/cloudinary-1.8.0.dist-info/metadata.json" />
        <File name="top_level" src="lib/cloudinary-1.8.0.dist-info/top_level.txt" />
        <File name="__init__" src="lib/cloudinary/__init__.py" />
        <File name="api" src="lib/cloudinary/api.py" />
        <File name="auth_token" src="lib/cloudinary/auth_token.py" />
        <File name="compat" src="lib/cloudinary/compat.py" />
        <File name="forms" src="lib/cloudinary/forms.py" />
        <File name="models" src="lib/cloudinary/models.py" />
        <File name="__init__" src="lib/cloudinary/poster/__init__.py" />
        <File name="encode" src="lib/cloudinary/poster/encode.py" />
        <File name="streaminghttp" src="lib/cloudinary/poster/streaminghttp.py" />
        <File name="search" src="lib/cloudinary/search.py" />
        <File name="cloudinary_cors" src="lib/cloudinary/static/html/cloudinary_cors.html" />
        <File name="canvas-to-blob.min" src="lib/cloudinary/static/js/canvas-to-blob.min.js" />
        <File name="jquery.cloudinary" src="lib/cloudinary/static/js/jquery.cloudinary.js" />
        <File name="jquery.fileupload-image" src="lib/cloudinary/static/js/jquery.fileupload-image.js" />
        <File name="jquery.fileupload-process" src="lib/cloudinary/static/js/jquery.fileupload-process.js" />
        <File name="jquery.fileupload-validate" src="lib/cloudinary/static/js/jquery.fileupload-validate.js" />
        <File name="jquery.fileupload" src="lib/cloudinary/static/js/jquery.fileupload.js" />
        <File name="jquery.iframe-transport" src="lib/cloudinary/static/js/jquery.iframe-transport.js" />
        <File name="jquery.ui.widget" src="lib/cloudinary/static/js/jquery.ui.widget.js" />
        <File name="load-image.all.min" src="lib/cloudinary/static/js/load-image.all.min.js" />
        <File name="cloudinary_direct_upload" src="lib/cloudinary/templates/cloudinary_direct_upload.html" />
        <File name="cloudinary_includes" src="lib/cloudinary/templates/cloudinary_includes.html" />
        <File name="cloudinary_js_config" src="lib/cloudinary/templates/cloudinary_js_config.html" />
        <File name="__init__" src="lib/cloudinary/templatetags/__init__.py" />
        <File name="cloudinary" src="lib/cloudinary/templatetags/cloudinary.py" />
        <File name="uploader" src="lib/cloudinary/uploader.py" />
        <File name="utils" src="lib/cloudinary/utils.py" />
        <File name="DESCRIPTION" src="lib/funcsigs-1.0.2.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/funcsigs-1.0.2.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/funcsigs-1.0.2.dist-info/METADATA" />
        <File name="RECORD" src="lib/funcsigs-1.0.2.dist-info/RECORD" />
        <File name="WHEEL" src="lib/funcsigs-1.0.2.dist-info/WHEEL" />
        <File name="metadata" src="lib/funcsigs-1.0.2.dist-info/metadata.json" />
        <File name="pbr" src="lib/funcsigs-1.0.2.dist-info/pbr.json" />
        <File name="top_level" src="lib/funcsigs-1.0.2.dist-info/top_level.txt" />
        <File name="__init__" src="lib/funcsigs/__init__.py" />
        <File name="version" src="lib/funcsigs/version.py" />
        <File name="DESCRIPTION" src="lib/idna-2.6.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/idna-2.6.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/idna-2.6.dist-info/METADATA" />
        <File name="RECORD" src="lib/idna-2.6.dist-info/RECORD" />
        <File name="WHEEL" src="lib/idna-2.6.dist-info/WHEEL" />
        <File name="metadata" src="lib/idna-2.6.dist-info/metadata.json" />
        <File name="top_level" src="lib/idna-2.6.dist-info/top_level.txt" />
        <File name="__init__" src="lib/idna/__init__.py" />
        <File name="codec" src="lib/idna/codec.py" />
        <File name="compat" src="lib/idna/compat.py" />
        <File name="core" src="lib/idna/core.py" />
        <File name="idnadata" src="lib/idna/idnadata.py" />
        <File name="intranges" src="lib/idna/intranges.py" />
        <File name="package_data" src="lib/idna/package_data.py" />
        <File name="uts46data" src="lib/idna/uts46data.py" />
        <File name="DESCRIPTION" src="lib/inflect-0.2.5.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/inflect-0.2.5.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/inflect-0.2.5.dist-info/METADATA" />
        <File name="RECORD" src="lib/inflect-0.2.5.dist-info/RECORD" />
        <File name="WHEEL" src="lib/inflect-0.2.5.dist-info/WHEEL" />
        <File name="metadata" src="lib/inflect-0.2.5.dist-info/metadata.json" />
        <File name="top_level" src="lib/inflect-0.2.5.dist-info/top_level.txt" />
        <File name="inflect" src="lib/inflect.py" />
        <File name="jaraco.itertools-2.0.1-py3.6-nspkg" src="lib/jaraco.itertools-2.0.1-py3.6-nspkg.pth" />
        <File name="DESCRIPTION" src="lib/jaraco.itertools-2.0.1.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/jaraco.itertools-2.0.1.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/jaraco.itertools-2.0.1.dist-info/METADATA" />
        <File name="RECORD" src="lib/jaraco.itertools-2.0.1.dist-info/RECORD" />
        <File name="WHEEL" src="lib/jaraco.itertools-2.0.1.dist-info/WHEEL" />
        <File name="metadata" src="lib/jaraco.itertools-2.0.1.dist-info/metadata.json" />
        <File name="namespace_packages" src="lib/jaraco.itertools-2.0.1.dist-info/namespace_packages.txt" />
        <File name="top_level" src="lib/jaraco.itertools-2.0.1.dist-info/top_level.txt" />
        <File name="itertools" src="lib/jaraco/itertools.py" />
        <File name="DESCRIPTION" src="lib/mock-2.0.0.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/mock-2.0.0.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/mock-2.0.0.dist-info/METADATA" />
        <File name="RECORD" src="lib/mock-2.0.0.dist-info/RECORD" />
        <File name="WHEEL" src="lib/mock-2.0.0.dist-info/WHEEL" />
        <File name="metadata" src="lib/mock-2.0.0.dist-info/metadata.json" />
        <File name="pbr" src="lib/mock-2.0.0.dist-info/pbr.json" />
        <File name="top_level" src="lib/mock-2.0.0.dist-info/top_level.txt" />
        <File name="__init__" src="lib/mock/__init__.py" />
        <File name="mock" src="lib/mock/mock.py" />
        <File name="__init__" src="lib/mock/tests/__init__.py" />
        <File name="__main__" src="lib/mock/tests/__main__.py" />
        <File name="support" src="lib/mock/tests/support.py" />
        <File name="testcallable" src="lib/mock/tests/testcallable.py" />
        <File name="testhelpers" src="lib/mock/tests/testhelpers.py" />
        <File name="testmagicmethods" src="lib/mock/tests/testmagicmethods.py" />
        <File name="testmock" src="lib/mock/tests/testmock.py" />
        <File name="testpatch" src="lib/mock/tests/testpatch.py" />
        <File name="testsentinel" src="lib/mock/tests/testsentinel.py" />
        <File name="testwith" src="lib/mock/tests/testwith.py" />
        <File name="DESCRIPTION" src="lib/more_itertools-3.2.0.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/more_itertools-3.2.0.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/more_itertools-3.2.0.dist-info/METADATA" />
        <File name="RECORD" src="lib/more_itertools-3.2.0.dist-info/RECORD" />
        <File name="WHEEL" src="lib/more_itertools-3.2.0.dist-info/WHEEL" />
        <File name="metadata" src="lib/more_itertools-3.2.0.dist-info/metadata.json" />
        <File name="top_level" src="lib/more_itertools-3.2.0.dist-info/top_level.txt" />
        <File name="__init__" src="lib/more_itertools/__init__.py" />
        <File name="more" src="lib/more_itertools/more.py" />
        <File name="recipes" src="lib/more_itertools/recipes.py" />
        <File name="__init__" src="lib/more_itertools/tests/__init__.py" />
        <File name="test_more" src="lib/more_itertools/tests/test_more.py" />
        <File name="test_recipes" src="lib/more_itertools/tests/test_recipes.py" />
        <File name="DESCRIPTION" src="lib/pbr-3.1.1.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/pbr-3.1.1.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/pbr-3.1.1.dist-info/METADATA" />
        <File name="RECORD" src="lib/pbr-3.1.1.dist-info/RECORD" />
        <File name="WHEEL" src="lib/pbr-3.1.1.dist-info/WHEEL" />
        <File name="entry_points" src="lib/pbr-3.1.1.dist-info/entry_points.txt" />
        <File name="metadata" src="lib/pbr-3.1.1.dist-info/metadata.json" />
        <File name="top_level" src="lib/pbr-3.1.1.dist-info/top_level.txt" />
        <File name="__init__" src="lib/pbr/__init__.py" />
        <File name="builddoc" src="lib/pbr/builddoc.py" />
        <File name="__init__" src="lib/pbr/cmd/__init__.py" />
        <File name="main" src="lib/pbr/cmd/main.py" />
        <File name="core" src="lib/pbr/core.py" />
        <File name="extra_files" src="lib/pbr/extra_files.py" />
        <File name="find_package" src="lib/pbr/find_package.py" />
        <File name="git" src="lib/pbr/git.py" />
        <File name="__init__" src="lib/pbr/hooks/__init__.py" />
        <File name="backwards" src="lib/pbr/hooks/backwards.py" />
        <File name="base" src="lib/pbr/hooks/base.py" />
        <File name="commands" src="lib/pbr/hooks/commands.py" />
        <File name="files" src="lib/pbr/hooks/files.py" />
        <File name="metadata" src="lib/pbr/hooks/metadata.py" />
        <File name="options" src="lib/pbr/options.py" />
        <File name="packaging" src="lib/pbr/packaging.py" />
        <File name="pbr_json" src="lib/pbr/pbr_json.py" />
        <File name="testr_command" src="lib/pbr/testr_command.py" />
        <File name="__init__" src="lib/pbr/tests/__init__.py" />
        <File name="base" src="lib/pbr/tests/base.py" />
        <File name="test_commands" src="lib/pbr/tests/test_commands.py" />
        <File name="test_core" src="lib/pbr/tests/test_core.py" />
        <File name="test_files" src="lib/pbr/tests/test_files.py" />
        <File name="test_hooks" src="lib/pbr/tests/test_hooks.py" />
        <File name="test_integration" src="lib/pbr/tests/test_integration.py" />
        <File name="test_packaging" src="lib/pbr/tests/test_packaging.py" />
        <File name="test_pbr_json" src="lib/pbr/tests/test_pbr_json.py" />
        <File name="test_setup" src="lib/pbr/tests/test_setup.py" />
        <File name="test_util" src="lib/pbr/tests/test_util.py" />
        <File name="test_version" src="lib/pbr/tests/test_version.py" />
        <File name="test_wsgi" src="lib/pbr/tests/test_wsgi.py" />
        <File name="CHANGES" src="lib/pbr/tests/testpackage/CHANGES.txt" />
        <File name="LICENSE" src="lib/pbr/tests/testpackage/LICENSE.txt" />
        <File name="MANIFEST" src="lib/pbr/tests/testpackage/MANIFEST.in" />
        <File name="README" src="lib/pbr/tests/testpackage/README.txt" />
        <File name="a" src="lib/pbr/tests/testpackage/data_files/a.txt" />
        <File name="b" src="lib/pbr/tests/testpackage/data_files/b.txt" />
        <File name="c" src="lib/pbr/tests/testpackage/data_files/c.rst" />
        <File name="conf" src="lib/pbr/tests/testpackage/doc/source/conf.py" />
        <File name="index" src="lib/pbr/tests/testpackage/doc/source/index.rst" />
        <File name="installation" src="lib/pbr/tests/testpackage/doc/source/installation.rst" />
        <File name="usage" src="lib/pbr/tests/testpackage/doc/source/usage.rst" />
        <File name="extra-file" src="lib/pbr/tests/testpackage/extra-file.txt" />
        <File name="git-extra-file" src="lib/pbr/tests/testpackage/git-extra-file.txt" />
        <File name="__init__" src="lib/pbr/tests/testpackage/pbr_testpackage/__init__.py" />
        <File name="_setup_hooks" src="lib/pbr/tests/testpackage/pbr_testpackage/_setup_hooks.py" />
        <File name="cmd" src="lib/pbr/tests/testpackage/pbr_testpackage/cmd.py" />
        <File name="extra" src="lib/pbr/tests/testpackage/pbr_testpackage/extra.py" />
        <File name="1" src="lib/pbr/tests/testpackage/pbr_testpackage/package_data/1.txt" />
        <File name="2" src="lib/pbr/tests/testpackage/pbr_testpackage/package_data/2.txt" />
        <File name="wsgi" src="lib/pbr/tests/testpackage/pbr_testpackage/wsgi.py" />
        <File name="setup" src="lib/pbr/tests/testpackage/setup.cfg" />
        <File name="setup" src="lib/pbr/tests/testpackage/setup.py" />
        <File name="testext" src="lib/pbr/tests/testpackage/src/testext.c" />
        <File name="test-requirements" src="lib/pbr/tests/testpackage/test-requirements.txt" />
        <File name="util" src="lib/pbr/tests/util.py" />
        <File name="util" src="lib/pbr/util.py" />
        <File name="version" src="lib/pbr/version.py" />
        <File name="DESCRIPTION" src="lib/requests-2.18.4.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/requests-2.18.4.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/requests-2.18.4.dist-info/METADATA" />
        <File name="RECORD" src="lib/requests-2.18.4.dist-info/RECORD" />
        <File name="WHEEL" src="lib/requests-2.18.4.dist-info/WHEEL" />
        <File name="metadata" src="lib/requests-2.18.4.dist-info/metadata.json" />
        <File name="top_level" src="lib/requests-2.18.4.dist-info/top_level.txt" />
        <File name="__init__" src="lib/requests/__init__.py" />
        <File name="__version__" src="lib/requests/__version__.py" />
        <File name="_internal_utils" src="lib/requests/_internal_utils.py" />
        <File name="adapters" src="lib/requests/adapters.py" />
        <File name="api" src="lib/requests/api.py" />
        <File name="auth" src="lib/requests/auth.py" />
        <File name="certs" src="lib/requests/certs.py" />
        <File name="compat" src="lib/requests/compat.py" />
        <File name="cookies" src="lib/requests/cookies.py" />
        <File name="exceptions" src="lib/requests/exceptions.py" />
        <File name="help" src="lib/requests/help.py" />
        <File name="hooks" src="lib/requests/hooks.py" />
        <File name="models" src="lib/requests/models.py" />
        <File name="packages" src="lib/requests/packages.py" />
        <File name="sessions" src="lib/requests/sessions.py" />
        <File name="status_codes" src="lib/requests/status_codes.py" />
        <File name="structures" src="lib/requests/structures.py" />
        <File name="utils" src="lib/requests/utils.py" />
        <File name="DESCRIPTION" src="lib/six-1.11.0.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/six-1.11.0.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/six-1.11.0.dist-info/METADATA" />
        <File name="RECORD" src="lib/six-1.11.0.dist-info/RECORD" />
        <File name="WHEEL" src="lib/six-1.11.0.dist-info/WHEEL" />
        <File name="metadata" src="lib/six-1.11.0.dist-info/metadata.json" />
        <File name="top_level" src="lib/six-1.11.0.dist-info/top_level.txt" />
        <File name="six" src="lib/six.py" />
        <File name="DESCRIPTION" src="lib/urllib3-1.22.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/urllib3-1.22.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/urllib3-1.22.dist-info/METADATA" />
        <File name="RECORD" src="lib/urllib3-1.22.dist-info/RECORD" />
        <File name="WHEEL" src="lib/urllib3-1.22.dist-info/WHEEL" />
        <File name="metadata" src="lib/urllib3-1.22.dist-info/metadata.json" />
        <File name="top_level" src="lib/urllib3-1.22.dist-info/top_level.txt" />
        <File name="__init__" src="lib/urllib3/__init__.py" />
        <File name="_collections" src="lib/urllib3/_collections.py" />
        <File name="connection" src="lib/urllib3/connection.py" />
        <File name="connectionpool" src="lib/urllib3/connectionpool.py" />
        <File name="__init__" src="lib/urllib3/contrib/__init__.py" />
        <File name="__init__" src="lib/urllib3/contrib/_securetransport/__init__.py" />
        <File name="bindings" src="lib/urllib3/contrib/_securetransport/bindings.py" />
        <File name="low_level" src="lib/urllib3/contrib/_securetransport/low_level.py" />
        <File name="appengine" src="lib/urllib3/contrib/appengine.py" />
        <File name="ntlmpool" src="lib/urllib3/contrib/ntlmpool.py" />
        <File name="pyopenssl" src="lib/urllib3/contrib/pyopenssl.py" />
        <File name="securetransport" src="lib/urllib3/contrib/securetransport.py" />
        <File name="socks" src="lib/urllib3/contrib/socks.py" />
        <File name="exceptions" src="lib/urllib3/exceptions.py" />
        <File name="fields" src="lib/urllib3/fields.py" />
        <File name="filepost" src="lib/urllib3/filepost.py" />
        <File name="__init__" src="lib/urllib3/packages/__init__.py" />
        <File name="__init__" src="lib/urllib3/packages/backports/__init__.py" />
        <File name="makefile" src="lib/urllib3/packages/backports/makefile.py" />
        <File name="ordered_dict" src="lib/urllib3/packages/ordered_dict.py" />
        <File name="six" src="lib/urllib3/packages/six.py" />
        <File name="__init__" src="lib/urllib3/packages/ssl_match_hostname/__init__.py" />
        <File name="_implementation" src="lib/urllib3/packages/ssl_match_hostname/_implementation.py" />
        <File name="poolmanager" src="lib/urllib3/poolmanager.py" />
        <File name="request" src="lib/urllib3/request.py" />
        <File name="response" src="lib/urllib3/response.py" />
        <File name="__init__" src="lib/urllib3/util/__init__.py" />
        <File name="connection" src="lib/urllib3/util/connection.py" />
        <File name="request" src="lib/urllib3/util/request.py" />
        <File name="response" src="lib/urllib3/util/response.py" />
        <File name="retry" src="lib/urllib3/util/retry.py" />
        <File name="selectors" src="lib/urllib3/util/selectors.py" />
        <File name="ssl_" src="lib/urllib3/util/ssl_.py" />
        <File name="timeout" src="lib/urllib3/util/timeout.py" />
        <File name="url" src="lib/urllib3/util/url.py" />
        <File name="wait" src="lib/urllib3/util/wait.py" />
        <File name="DESCRIPTION" src="lib/wikipedia-1.4.0.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/wikipedia-1.4.0.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/wikipedia-1.4.0.dist-info/METADATA" />
        <File name="RECORD" src="lib/wikipedia-1.4.0.dist-info/RECORD" />
        <File name="WHEEL" src="lib/wikipedia-1.4.0.dist-info/WHEEL" />
        <File name="metadata" src="lib/wikipedia-1.4.0.dist-info/metadata.json" />
        <File name="top_level" src="lib/wikipedia-1.4.0.dist-info/top_level.txt" />
        <File name="__init__" src="lib/wikipedia/__init__.py" />
        <File name="exceptions" src="lib/wikipedia/exceptions.py" />
        <File name="util" src="lib/wikipedia/util.py" />
        <File name="wikipedia" src="lib/wikipedia/wikipedia.py" />
        <File name="DESCRIPTION" src="lib/wolframalpha-3.0.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/wolframalpha-3.0.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/wolframalpha-3.0.dist-info/METADATA" />
        <File name="RECORD" src="lib/wolframalpha-3.0.dist-info/RECORD" />
        <File name="WHEEL" src="lib/wolframalpha-3.0.dist-info/WHEEL" />
        <File name="entry_points" src="lib/wolframalpha-3.0.dist-info/entry_points.txt" />
        <File name="metadata" src="lib/wolframalpha-3.0.dist-info/metadata.json" />
        <File name="namespace_packages" src="lib/wolframalpha-3.0.dist-info/namespace_packages.txt" />
        <File name="top_level" src="lib/wolframalpha-3.0.dist-info/top_level.txt" />
        <File name="__init__" src="lib/wolframalpha/__init__.py" />
        <File name="compat" src="lib/wolframalpha/compat.py" />
        <File name="pmxbot" src="lib/wolframalpha/pmxbot.py" />
        <File name="test_client" src="lib/wolframalpha/test_client.py" />
        <File name="test_pmxbot" src="lib/wolframalpha/test_pmxbot.py" />
        <File name="DESCRIPTION" src="lib/xmltodict-0.11.0.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/xmltodict-0.11.0.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/xmltodict-0.11.0.dist-info/METADATA" />
        <File name="RECORD" src="lib/xmltodict-0.11.0.dist-info/RECORD" />
        <File name="WHEEL" src="lib/xmltodict-0.11.0.dist-info/WHEEL" />
        <File name="metadata" src="lib/xmltodict-0.11.0.dist-info/metadata.json" />
        <File name="top_level" src="lib/xmltodict-0.11.0.dist-info/top_level.txt" />
        <File name="xmltodict" src="lib/xmltodict.py" />
        <File name="pepper-icons" src="html/pepper-icons.jpg" />
        <File name="pepper-icons2" src="html/pepper-icons2.jpg" />
        <File name="pepper-icons3" src="html/pepper-icons3.png" />
        <File name="index" src="html/index.html" />
        <File name="script" src="html/script.js" />
        <File name="typed.min" src="html/typed.min.js" />
    </Resources>
    <Topics>
        <Topic name="topic_dialog_enu" src="topic_dialog/topic_dialog_enu.top" topicName="topic_dialog" language="en_US" />
    </Topics>
    <IgnoredPaths />
    <Translations auto-fill="en_US">
        <Translation name="translation_en_US" src="translations/translation_en_US.ts" language="en_US" />
    </Translations>
</Package>
